trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@2
  inputs:
    versionSpec: '14.x'
  displayName: 'Instalar Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Instalar dependencias y construir'

- script: |
    npm test
  displayName: 'Ejecutar pruebas'
